export const SHOW_CHARACTERS_MOVIES = 'SHOW_CHARACTERS_MOVIES';
export const SHOW_CHARACTERS_LIST = 'SHOW_CHARACTERS_LIST';
export const SET_CHARACTERS = 'SET_CHARACTERS';
export const FETCH_CHARACTERS_FAILED = 'FETCH_CHARACTERS_FAILED';
